---
- name: Update all packages to their latest version
  dnf:
    name: "*"
    state: latest
  become: true

- name: Remove Java 1.8.0
  dnf:
    name: "java-1.8.0-openjdk"
    state: removed
  become: true

- name: Install required packages
  apt:
    pkg:
      - java-latest-openjdk
      - screen
    state: present
  become: true
  tags: minecraft

- name: Open port 25565
  firewalld:
    port: "25565/tcp"
    permanent: true
    state: enabled
    immediate: yes
    notify: firewall reload
  become: true
  tags: nginx

- name: Download minecraft server
  get_url:
    url: https://launcher.mojang.com/v1/objects/a16d67e5807f57fc4e550299cf20226194497dc2/server.jar
    dest: /home/minecraft
  become: true

- name: accept Eula
  template:
    src: "files/eula.txt.tpl"
    dest: /home/minecraft/eula.txt
  become: true

- name: add properties
  template:
    src: "files/server.properties.tpl"
    dest: /home/minecraft/server.properties
  become: true

- name: add logs
  template:
    src: "files/latest.log.tpl"
    dest: /home/minecraft/logs/latest.log
  become: true

- name: Start screen
  command: screen -S "Minecraft server"
  tags: minecraft

- name: Start server
  command: java -Xms1024M -jar server.jar nogui

